// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWCd-1bkdyq1wUzWYfGQ3F9olss5K_Q-8',
    appId: '1:639403984663:android:f18eb1a46683fc5a1b9952',
    messagingSenderId: '639403984663',
    projectId: 'gooway-9d5d9',
    storageBucket: 'gooway-9d5d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-JRrchnLSuCDsUbUHm_yPgxL1_CRqi5s',
    appId: '1:639403984663:ios:f9be5f2fa2cb28fc1b9952',
    messagingSenderId: '639403984663',
    projectId: 'gooway-9d5d9',
    storageBucket: 'gooway-9d5d9.firebasestorage.app',
    iosClientId: '639403984663-phjjbtguqqse89ef6g4308ohp4jspt2e.apps.googleusercontent.com',
    iosBundleId: 'com.gooway.turismoCartagena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-JRrchnLSuCDsUbUHm_yPgxL1_CRqi5s',
    appId: '1:639403984663:ios:500a49773feef8d51b9952',
    messagingSenderId: '639403984663',
    projectId: 'gooway-9d5d9',
    storageBucket: 'gooway-9d5d9.firebasestorage.app',
    iosClientId: '639403984663-sm466fcpodto32ho71lts62juepg4bcq.apps.googleusercontent.com',
    iosBundleId: 'com.simasoftturismocartagena.turismoCartagena',
  );
}
